org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.234
loader_version_range=[4,)

simple_bedrock_model_version=2.5.1.1-neoforge-mc1.21.1
mae_version=1.1.4

mod_id=better_trident_model
mod_name=BetterTridentModel
mod_license=GNU LGPL 3.0
mod_version=1.2.0
mod_group_id=com.p1nero.btm
mod_authors=P1nero
mod_description=Replace the trident model
